# Generated by Django 3.2.19 on 2023-10-18 03:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import native_shortuuid.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('employee_id', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='员工ID')),
                ('employee_name', models.CharField(max_length=20, verbose_name='员工姓名')),
                ('employee_department', models.CharField(max_length=20, verbose_name='所属部门')),
            ],
            options={
                'verbose_name': '员工信息',
                'verbose_name_plural': '员工信息',
                'db_table': 't_employee',
            },
        ),
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('id', native_shortuuid.fields.NativeShortUUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('visitor_name', models.CharField(max_length=20, verbose_name='访客姓名')),
                ('visitor_mobile', models.CharField(max_length=11, verbose_name='访客手机号')),
                ('visitor_num', models.PositiveSmallIntegerField(verbose_name='访客人数')),
                ('visit_date', models.DateTimeField(verbose_name='到访时间日期')),
                ('visitor_car_number', models.CharField(blank=True, max_length=10, null=True, verbose_name='车牌号码')),
                ('visitor_reason', models.CharField(max_length=50, verbose_name='来访原因')),
                ('visitor_unit', models.CharField(blank=True, max_length=20, null=True, verbose_name='所属单位')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, '未到访'), (1, '已到访')], default=0, verbose_name='当前状态')),
                ('employee', models.ForeignKey(db_column='employee_id', on_delete=django.db.models.deletion.RESTRICT, related_name='invites', to='invite.employee', verbose_name='邀请人')),
            ],
            options={
                'verbose_name': '访客信息',
                'verbose_name_plural': '访客信息',
                'db_table': 't_invite',
            },
        ),
    ]
